const rarityMeta={COMMON:{mp:3,color:'#aeb7c3',rank:1},UNCOMMON:{mp:5,color:'#62e899',rank:2},RARE:{mp:8,color:'#57a6ff',rank:3},EPIC:{mp:12,color:'#b878ff',rank:4},LEGENDARY:{mp:16,color:'#ffb84d',rank:5},MYTHIC:{mp:22,color:'#ff6ca8',rank:6},SPECIAL:{mp:3,color:'#ff6868',rank:7}};
const $=selector=>document.querySelector(selector);let accessories=[],textures={},activeRarity='ALL';
const grid=$('#accessoryGrid'),search=$('#searchInput'),sourceFilter=$('#sourceFilter'),empty=$('#emptyState');

async function loadCatalog(){const [catalogResponse,textureResponse]=await Promise.all([fetch('./data/accessories.json'),fetch('./generated/furfsky/manifest.json')]);if(!catalogResponse.ok)throw new Error('Accessory database unavailable');accessories=(await catalogResponse.json()).accessories;textures=textureResponse.ok?(await textureResponse.json()).icons||{}:{};setupFilters();updateTotals();render()}
function setupFilters(){const rarities=['ALL',...Object.keys(rarityMeta).filter(rarity=>accessories.some(item=>item.rarity===rarity))];$('#rarityFilters').innerHTML=rarities.map((rarity,index)=>`<button class="${index===0?'active':''}" data-rarity="${rarity}">${rarity[0]+rarity.slice(1).toLowerCase()}</button>`).join('');[...new Set(accessories.map(item=>item.source))].sort().forEach(source=>sourceFilter.insertAdjacentHTML('beforeend',`<option value="${source}">${source}</option>`))}
function updateTotals(){$('#totalCount').textContent=accessories.length;$('#familyCount').textContent=new Set(accessories.map(item=>item.family)).size;const best={};accessories.forEach(item=>best[item.family]=Math.max(best[item.family]||0,rarityMeta[item.rarity].mp));$('#maxMp').textContent=Object.values(best).reduce((total,mp)=>total+mp,0)}
const initials=name=>name.split(/\s+/).filter(word=>!['of','the'].includes(word.toLowerCase())).slice(0,2).map(word=>word[0]).join('').toUpperCase();
const localPath=src=>src.startsWith('/')?`.${src}`:src;
function textureIcon(item){const custom=textures[item.id],texture=custom||item.fallbackTexture;if(!texture)return `<span>${initials(item.name)}</span>`;const entry=typeof texture==='string'?{src:texture}:texture,src=localPath(entry.src);if(!entry.animation)return `<img class="${!custom&&item.fallbackTextureType==='head'?'head-render':''}" src="${src}" alt="" loading="lazy"><span>${initials(item.name)}</span>`;return `<canvas class="animated-texture" width="${entry.animation.frameWidth}" height="${entry.animation.frameHeight}" data-src="${src}" data-animation="${encodeURIComponent(JSON.stringify(entry.animation))}" aria-hidden="true"></canvas><span>${initials(item.name)}</span>`}
function startTextureAnimations(){document.querySelectorAll('.animated-texture').forEach(canvas=>{const image=new Image(),animation=JSON.parse(decodeURIComponent(canvas.dataset.animation)),context=canvas.getContext('2d');context.imageSmoothingEnabled=false;image.onload=()=>{const total=animation.frames.reduce((sum,frame)=>sum+frame.time*50,0),started=performance.now();const paint=now=>{if(!canvas.isConnected)return;let position=(now-started)%total,current=0,elapsed=0;for(let index=0;index<animation.frames.length;index++){const duration=animation.frames[index].time*50;if(position<elapsed+duration){current=index;position-=elapsed;break}elapsed+=duration}const frame=animation.frames[current],next=animation.frames[(current+1)%animation.frames.length];context.clearRect(0,0,canvas.width,canvas.height);context.globalAlpha=1;context.drawImage(image,0,frame.index*animation.frameHeight,animation.frameWidth,animation.frameHeight,0,0,canvas.width,canvas.height);if(animation.interpolate){context.globalAlpha=position/(frame.time*50);context.drawImage(image,0,next.index*animation.frameHeight,animation.frameWidth,animation.frameHeight,0,0,canvas.width,canvas.height);context.globalAlpha=1}requestAnimationFrame(paint)};requestAnimationFrame(paint)};image.src=canvas.dataset.src})}
function render(){const query=search.value.trim().toLowerCase();const items=accessories.filter(item=>(activeRarity==='ALL'||item.rarity===activeRarity)&&(sourceFilter.value==='all'||item.source===sourceFilter.value)&&(!query||`${item.name} ${item.source} ${item.route}`.toLowerCase().includes(query))).sort((a,b)=>rarityMeta[a.rarity].rank-rarityMeta[b.rarity].rank||a.name.localeCompare(b.name));grid.innerHTML=items.map(item=>`<article class="card" style="--rarity-color:${rarityMeta[item.rarity].color}"><div class="card-top"><div class="item-icon furfsky-icon">${textureIcon(item)}</div><span class="rarity">${item.rarity}</span></div><h3 title="${item.name}">${item.name}</h3><p class="route">${item.route}</p><div class="card-foot"><span class="source">${item.source}</span><span class="mp"><strong>+${rarityMeta[item.rarity].mp}</strong> MP</span></div></article>`).join('');startTextureAnimations();$('#resultCount').textContent=items.length;empty.hidden=items.length>0}

$('#rarityFilters').addEventListener('click',event=>{if(!event.target.dataset.rarity)return;activeRarity=event.target.dataset.rarity;document.querySelectorAll('#rarityFilters button').forEach(button=>button.classList.toggle('active',button===event.target));render()});[search,sourceFilter].forEach(element=>element.addEventListener('input',render));document.querySelectorAll('.view-toggle button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.view-toggle button').forEach(candidate=>candidate.classList.toggle('active',candidate===button));grid.classList.toggle('list-view',button.dataset.view==='list')}));
loadCatalog().catch(error=>{grid.innerHTML=`<div class="empty-state"><h2>${error.message}</h2><p>Serve this folder from any static web host.</p></div>`});
