const rarityMeta={COMMON:{mp:3,color:'#aeb7c3',rank:1},UNCOMMON:{mp:5,color:'#62e899',rank:2},RARE:{mp:8,color:'#57a6ff',rank:3},EPIC:{mp:12,color:'#b878ff',rank:4},LEGENDARY:{mp:16,color:'#ffb84d',rank:5},MYTHIC:{mp:22,color:'#ff6ca8',rank:6},SPECIAL:{mp:3,color:'#ff6868',rank:7},VERY_SPECIAL:{mp:5,color:'#ff6868',rank:8}};
const $=selector=>document.querySelector(selector);let accessories=[],familyUpgrades={},minions=[],textures={},activeRarity='ALL',activeMinionCategory='ALL',profile=null,profileOptionsUsername='';
const grid=$('#accessoryGrid'),search=$('#searchInput'),sourceFilter=$('#sourceFilter'),statusFilter=$('#statusFilter'),empty=$('#emptyState');
async function loadCatalog(){const [catalogResponse,minionResponse,textureResponse]=await Promise.all([fetch('./data/accessories.json'),fetch('./data/minions.json'),fetch('./generated/furfsky/manifest.json')]);if(!catalogResponse.ok||!minionResponse.ok)throw new Error('Progression database unavailable');const catalog=await catalogResponse.json(),minionCatalog=await minionResponse.json();accessories=catalog.accessories;familyUpgrades=catalog.familyUpgrades||{};minions=minionCatalog.minions||[];textures=textureResponse.ok?(await textureResponse.json()).icons||{}:{};setupFilters();setupMinionFilters();updateTotals();render();renderMinions()}
const catalogRarity=item=>item.maxRarity||item.rarity;
function setupFilters(){const rarities=['ALL',...Object.keys(rarityMeta).filter(rarity=>accessories.some(item=>catalogRarity(item)===rarity))];$('#rarityFilters').innerHTML=rarities.map((rarity,index)=>`<button class="${index===0?'active':''}" data-rarity="${rarity}">${rarity[0]+rarity.slice(1).toLowerCase()}</button>`).join('');[...new Set(accessories.map(item=>item.source))].sort().forEach(source=>sourceFilter.insertAdjacentHTML('beforeend',`<option value="${source}">${source}</option>`))}
function setupMinionFilters(){const categories=['ALL',...new Set(minions.map(minion=>minion.category))];$('#minionCategories').innerHTML=categories.map((category,index)=>`<button class="${index===0?'active':''}" data-category="${category}">${category[0]+category.slice(1).toLowerCase()}</button>`).join('')}
function updateTotals(){$('#totalCount').textContent=accessories.length;$('#familyCount').textContent=new Set(accessories.map(item=>item.family)).size;const best={};accessories.forEach(item=>{const current=best[item.family];if(!current||rarityMeta[catalogRarity(item)].rank>rarityMeta[catalogRarity(current)].rank)best[item.family]=item});const familyMaxima=Object.values(best),base=familyMaxima.reduce((sum,item)=>sum+magicalPowerFor(catalogRarity(item)),0),recombined=familyMaxima.reduce((sum,item)=>{const rarity=catalogRarity(item),upgraded=item.canRecombobulate?rarityAfter(rarity):null;return sum+magicalPowerFor(upgraded||rarity)},0);$('#maxMp').textContent=recombined.toLocaleString();$('#maxMpLabel').textContent=`max rarity AP · ${base.toLocaleString()} base`}
const initials=name=>name.split(/\s+/).filter(word=>!['of','the'].includes(word.toLowerCase())).slice(0,2).map(word=>word[0]).join('').toUpperCase();
const staticAssetPath=src=>src?.startsWith('/')?`.${src}`:src;
function textureIcon(item){const custom=textures[item.id],texture=custom||item.fallbackTexture;if(!texture)return `<span>${initials(item.name)}</span>`;const entry=typeof texture==='string'?{src:texture}:texture,src=staticAssetPath(entry.src);if(!entry.animation)return `<img class="${!custom&&item.fallbackTextureType==='head'?'head-render':''}" src="${src}" alt="" loading="lazy"><span>${initials(item.name)}</span>`;return `<canvas class="animated-texture" width="${entry.animation.frameWidth}" height="${entry.animation.frameHeight}" data-src="${src}" data-animation="${encodeURIComponent(JSON.stringify(entry.animation))}"></canvas><span>${initials(item.name)}</span>`}
function startTextureAnimations(){document.querySelectorAll('.animated-texture').forEach(canvas=>{const image=new Image(),animation=JSON.parse(decodeURIComponent(canvas.dataset.animation)),context=canvas.getContext('2d');context.imageSmoothingEnabled=false;image.onload=()=>{const total=animation.frames.reduce((sum,frame)=>sum+frame.time*50,0),started=performance.now();const paint=now=>{if(!canvas.isConnected)return;let position=(now-started)%total,current=0,elapsed=0;for(let index=0;index<animation.frames.length;index++){const duration=animation.frames[index].time*50;if(position<elapsed+duration){current=index;position-=elapsed;break}elapsed+=duration}const frame=animation.frames[current],next=animation.frames[(current+1)%animation.frames.length];context.clearRect(0,0,canvas.width,canvas.height);context.globalAlpha=1;context.drawImage(image,0,frame.index*animation.frameHeight,animation.frameWidth,animation.frameHeight,0,0,canvas.width,canvas.height);if(animation.interpolate){context.globalAlpha=position/(frame.time*50);context.drawImage(image,0,next.index*animation.frameHeight,animation.frameWidth,animation.frameHeight,0,0,canvas.width,canvas.height);context.globalAlpha=1}requestAnimationFrame(paint)};requestAnimationFrame(paint)};image.src=canvas.dataset.src})}
const familyMembers=family=>accessories.filter(candidate=>candidate.family===family).sort((a,b)=>a.order-b.order);
function profileAccessoryDescriptor(id){const normalized=String(id||'').toUpperCase(),direct=accessories.find(item=>(item.profileIds||[item.id]).includes(normalized));if(direct){const members=familyMembers(direct.family);return{family:direct.family,level:members.findIndex(item=>item.id===direct.id),catalogItem:direct,external:false}}for(const [family,ids] of Object.entries(familyUpgrades)){const externalIndex=ids.indexOf(normalized);if(externalIndex<0)continue;const members=familyMembers(family);return{family,level:members.length+externalIndex,catalogItem:members.at(-1)||null,external:true}}return null}
const activeAccessoryIds=()=>new Set(profile?.items?.accessoryIds||profile?.items?.ids||[]);
const ownsItem=(item,ids=activeAccessoryIds())=>(item.profileIds||[item.id]).some(id=>ids.has(id));
const ownedAccessoryRecords=item=>(profile?.items?.accessories||[]).filter(record=>profileAccessoryDescriptor(record.id)?.catalogItem?.id===item.id);
const canRecombobulateItem=item=>ownedAccessoryRecords(item).some(record=>record.canRecombobulate&&record.unrecombobulatedCount>0);
const isRecombinedFamilyCompletion=item=>{const record=ownedAccessoryRecords(item).find(candidate=>candidate.recombobulatedCount>0);if(!record)return false;const descriptor=profileAccessoryDescriptor(record.id),maximumLevel=familyMembers(item.family).length+(familyUpgrades[item.family]||[]).length-1;return descriptor?.level===maximumLevel};
function hidesOwnedLowerFamilyMember(item){if(!profile)return false;const members=familyMembers(item.family),index=members.findIndex(candidate=>candidate.id===item.id),record=(profile.items?.accessories||[]).find(candidate=>profileAccessoryDescriptor(candidate.id)?.family===item.family),descriptor=record&&profileAccessoryDescriptor(record.id);if(!descriptor)return false;return index<Math.min(descriptor.level,members.length-1)}
const normalizeRarity=rarity=>String(rarity||'').trim().toUpperCase().replaceAll(' ','_');
const rarityAfter=rarity=>({COMMON:'UNCOMMON',UNCOMMON:'RARE',RARE:'EPIC',EPIC:'LEGENDARY',LEGENDARY:'MYTHIC',SPECIAL:'VERY_SPECIAL'}[normalizeRarity(rarity)]||null);
const rarityBefore=rarity=>({UNCOMMON:'COMMON',RARE:'UNCOMMON',EPIC:'RARE',LEGENDARY:'EPIC',MYTHIC:'LEGENDARY',VERY_SPECIAL:'SPECIAL'}[normalizeRarity(rarity)]||null);
const magicalPowerFor=rarity=>rarityMeta[normalizeRarity(rarity)]?.mp||0;
function familyUpgradeMpGain(item){const family=accessories.filter(candidate=>candidate.family===item.family).sort((a,b)=>a.order-b.order),index=family.findIndex(candidate=>candidate.id===item.id),previous=index>0?family[index-1]:null;return Math.max(0,magicalPowerFor(catalogRarity(item))-(previous?magicalPowerFor(catalogRarity(previous)):0))}
function displayedMpGain(item,recombable,completed){if(recombable){const record=ownedAccessoryRecords(item).find(candidate=>candidate.canRecombobulate&&candidate.unrecombobulatedCount>0),next=rarityAfter(record?.rarity||item.rarity);if(next)return Math.max(0,magicalPowerFor(next)-magicalPowerFor(record?.rarity||item.rarity))}if(completed){const record=ownedAccessoryRecords(item).find(candidate=>candidate.recombobulatedCount>0),base=record?.baseRarity||item.rarity;if(record)return Math.max(0,magicalPowerFor(record.rarity)-magicalPowerFor(base))}if(profile){const family=accessories.filter(candidate=>candidate.family===item.family).sort((a,b)=>a.order-b.order),index=family.findIndex(candidate=>candidate.id===item.id),previous=index>0?family[index-1]:null,record=ownedAccessoryRecords(item).sort((a,b)=>(rarityMeta[b.rarity]?.rank||0)-(rarityMeta[a.rarity]?.rank||0))[0];if(record)return Math.max(0,magicalPowerFor(record.rarity)-(previous?magicalPowerFor(catalogRarity(previous)):0))}return familyUpgradeMpGain(item)}
const escapeHtml=value=>String(value).replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
function blocker(item){if(!profile)return null;const ids=activeAccessoryIds(),family=accessories.filter(candidate=>candidate.family===item.family).sort((a,b)=>a.order-b.order),index=family.findIndex(candidate=>candidate.id===item.id);if(index>0&&!ownsItem(family[index-1],ids))return `Obtain ${family[index-1].name} first`;if(!item.unlock)return null;const gate=item.unlock;if(gate.type==='collection'){const exists=Object.prototype.hasOwnProperty.call(profile.collections,gate.id),progress=Number(profile.collections[gate.id]||0);if(!exists)return `Find ${gate.name} to unlock its collection`;return progress<gate.amount?`Reach ${gate.name} ${toRoman(gate.tier)} · ${progress.toLocaleString()}/${gate.amount.toLocaleString()}`:null}if(gate.type==='slayer'){const level=Number(profile.slayers?.[gate.id]||0);return level<gate.level?`Reach ${gate.name} ${gate.level} · currently ${level}`:null}if(gate.type==='skill'){const xp=Number(profile.skills?.[gate.id]||0);return xp<gate.amount?`Reach ${gate.name} ${gate.level} · ${Math.floor(xp).toLocaleString()}/${gate.amount.toLocaleString()} XP`:null}return null}
const toRoman=number=>['','I','II','III','IV','V','VI','VII','VIII','IX','X','XI'][number]||String(number);
function itemStatus(item){if(!profile)return null;const ids=activeAccessoryIds(),family=accessories.filter(candidate=>candidate.family===item.family).sort((a,b)=>a.order-b.order),index=family.findIndex(candidate=>candidate.id===item.id),ownsExternalHigher=(familyUpgrades[item.family]||[]).some(id=>ids.has(id));if(ownsItem(item,ids)||family.slice(index+1).some(candidate=>ownsItem(candidate,ids))||ownsExternalHigher)return'owned';if(blocker(item))return'blocked';const earlier=index>0&&family.slice(0,index).some(candidate=>ownsItem(candidate,ids)),requirements=item.requirements||[],materialsReady=requirements.length&&requirements.every(requirement=>requirement.type==='item'?(profile.items.counts[requirement.id]||0)>=requirement.amount:(profile.collections[requirement.id]||0)>=requirement.amount);if(materialsReady&&(index===0||earlier))return'ready';if(earlier)return'upgrade';return'missing'}
function familyUpgradeProgress(item){const ids=activeAccessoryIds(),family=accessories.filter(candidate=>candidate.family===item.family).sort((a,b)=>a.order-b.order),highestOwned=family.reduce((highest,candidate,index)=>ownsItem(candidate,ids)?index:highest,-1);return{current:Math.max(0,highestOwned+1),total:family.length}}
function matchesStatus(item){if(!profile||statusFilter.value==='all')return true;if(statusFilter.value==='recomb')return canRecombobulateItem(item);const status=itemStatus(item);return statusFilter.value==='upgrades'?(status==='upgrade'||status==='ready'):status===statusFilter.value}
function render(){const query=search.value.trim().toLowerCase();const items=accessories.filter(item=>!hidesOwnedLowerFamilyMember(item)&&(activeRarity==='ALL'||catalogRarity(item)===activeRarity)&&(sourceFilter.value==='all'||item.source===sourceFilter.value)&&matchesStatus(item)&&(!query||`${item.name} ${item.source} ${item.route}`.toLowerCase().includes(query))).sort((a,b)=>rarityMeta[catalogRarity(a)].rank-rarityMeta[catalogRarity(b)].rank||a.name.localeCompare(b.name));if(profile&&statusFilter.value==='all'){const rank={ready:0,upgrade:1,recomb:2,missing:3,blocked:4,owned:5,completed:6},sortState=item=>isRecombinedFamilyCompletion(item)?'completed':canRecombobulateItem(item)?'recomb':itemStatus(item);items.sort((a,b)=>rank[sortState(a)]-rank[sortState(b)])}grid.innerHTML=items.map(item=>{const status=itemStatus(item),recombable=canRecombobulateItem(item),completed=isRecombinedFamilyCompletion(item),mpGain=displayedMpGain(item,recombable,completed),isBase=accessories.filter(candidate=>candidate.family===item.family).sort((a,b)=>a.order-b.order)[0]?.id===item.id,readyLabel=item.source==='Villager'?'◆ Trade materials ready':item.source==='Events'?'◆ Event materials ready':isBase?'◆ Ready to craft':'◆ Ready to upgrade',upgradeProgress=familyUpgradeProgress(item),label=status==='blocked'?`⊘ ${blocker(item)}`:completed?'✦ Recombobulated':recombable?'◇ Recomb available':{owned:'✓ Owned',upgrade:`↑ Upgrade (${upgradeProgress.current}/${upgradeProgress.total})`,ready:readyLabel,missing:'Missing'}[status],labelClass=completed?'completed':recombable?'recomb':status,displayRarity=item.maxRarity?`${item.rarity}–${item.maxRarity}`:item.rarity;return `<article class="card ${status||''} ${recombable?'recombable':''} ${completed?'recombined-complete':''} ${profile?'profiled':''}" style="--rarity-color:${rarityMeta[catalogRarity(item)].color}">${status==='owned'?'<span class="owned-sheen"></span>':''}<div class="card-top"><div class="item-icon furfsky-icon">${textureIcon(item)}</div><span class="rarity">${displayRarity}</span></div><h3>${item.name}</h3><p class="route">${item.route}</p><div class="card-foot"><span class="source">${item.source}</span><span class="mp"><strong>+${mpGain}</strong> AP</span></div>${status?`<span class="card-status ${labelClass}">${label}</span>`:''}</article>`}).join('');startTextureAnimations();$('#resultCount').textContent=items.length;empty.hidden=items.length>0}
const minionProgress=minion=>{const crafted=new Set(profile?.minions?.crafted||[]),highest=Math.max(0,...minion.tiers.filter(tier=>crafted.has(tier.id)).map(tier=>tier.tier)),next=minion.tiers.find(tier=>tier.tier===highest+1)||null;return{highest,next,maxed:!next&&highest>0}};
function minionBlocker(minion,progress){if(!profile)return null;const previousId=`${minion.id}_GENERATOR_${progress.next?.tier-1}`,crafted=new Set(profile.minions?.crafted||[]);if(progress.next?.tier>1&&!crafted.has(previousId))return `Craft ${minion.name} ${toRoman(progress.next.tier-1)} first`;if(progress.next?.tier===1&&minion.acquisition&&!progress.next.requirements.length)return minion.acquisition;const gate=minion.unlockGate;if(!gate||progress.highest)return null;if(gate.type==='collection'){const amount=Number(profile.collections?.[gate.id]||0);if(amount<gate.amount)return `Reach ${gate.name} ${toRoman(gate.tier)} · ${amount.toLocaleString()}/${gate.amount.toLocaleString()}`}if(gate.type==='slayer'){const level=Number(profile.slayers?.[gate.id]||0);if(level<gate.level)return `Reach ${gate.name} ${gate.level} · currently ${level}`}return null}
function minionState(minion){if(!profile)return null;const progress=minionProgress(minion);if(progress.maxed)return'maxed';if(minionBlocker(minion,progress))return progress.highest?'unlocked':'blocked';const ready=progress.next?.requirements.length>0&&progress.next.requirements.every(requirement=>(profile.items.counts[requirement.id]||0)>=requirement.amount);return ready?'ready':progress.highest?'unlocked':'blocked'}
const materialName=id=>id.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase()),headRenderUrl=url=>{const hash=url?.split('/').filter(Boolean).pop();return hash?`https://mc-heads.net/head/${hash}/64`:url};
function renderMinions(){const query=$('#minionSearch').value.trim().toLowerCase(),filter=$('#minionStatus').value,sort=$('#minionSort').value;let list=minions.filter(minion=>(activeMinionCategory==='ALL'||minion.category===activeMinionCategory)&&(!query||`${minion.name} ${minion.category}`.toLowerCase().includes(query))&&(!profile||filter==='all'||minionState(minion)===filter));const rank={ready:0,unlocked:1,blocked:2,maxed:3};list.sort((a,b)=>sort==='lowest-tier'?minionProgress(a).highest-minionProgress(b).highest||a.name.localeCompare(b.name):sort==='name'?a.name.localeCompare(b.name):sort==='category'?a.category.localeCompare(b.category)||a.name.localeCompare(b.name):profile?rank[minionState(a)]-rank[minionState(b)]||a.name.localeCompare(b.name):a.name.localeCompare(b.name));const crafted=new Set(profile?.minions?.crafted||[]);$('#minionGrid').innerHTML=list.map(minion=>{const progress=minionProgress(minion),state=minionState(minion),target=progress.next,block=state==='blocked'||state==='unlocked'?minionBlocker(minion,progress):null,label=!profile?minion.unlock||'Craftable on Stranded':state==='ready'?`${target.tier===1?'Craft':'Upgrade to'} tier ${toRoman(target.tier)} now`:state==='maxed'?'✓ Max tier crafted':block?`⊘ ${block}`:progress.highest?`Tier ${toRoman(progress.highest)} unlocked`:'Not unlocked',requirements=target?.requirements||[];return `<article class="card minion-card ${state||''} ${profile?'profiled':''}" style="--rarity-color:#57a6ff">${state==='maxed'?'<span class="owned-sheen"></span>':''}<div class="card-top"><div class="item-icon furfsky-icon">${minion.texture?`<img class="head-render" src="${headRenderUrl(minion.texture)}" alt="" loading="lazy">`:`<span>${initials(minion.name)}</span>`}</div><span class="rarity">${minion.category}</span></div><h3>${minion.name}</h3><p class="route">${progress.highest?`Highest crafted: Tier ${toRoman(progress.highest)}`:`Unlock: ${minion.unlock||'Special recipe'}`}</p>${target?`<div class="minion-materials">${requirements.map(requirement=>{const have=profile?.items?.counts?.[requirement.id]||0,met=have>=requirement.amount;return `<span class="${met?'met':''}">${profile?`${Math.min(have,requirement.amount).toLocaleString()}/`:''}${requirement.amount.toLocaleString()} ${materialName(requirement.id)}</span>`}).join('')}</div>`:''}<span class="card-status ${state||'missing'}">${label}</span></article>`}).join('');$('#minionResultCount').textContent=list.length;$('#minionEmpty').hidden=list.length>0;if(profile){const progresses=minions.map(minionProgress),states=minions.map(minionState);$('#minionUnlocked').textContent=progresses.filter(item=>item.highest>0).length;$('#minionReady').textContent=states.filter(state=>state==='ready').length;$('#minionUnique').textContent=crafted.size}else{$('#minionUnlocked').textContent='—';$('#minionReady').textContent='—';$('#minionUnique').textContent='—'}}
const nextRarity=rarity=>(rarityAfter(rarity)||'NEXT_RARITY').replaceAll('_',' ');
function updateRecombobulationSummary(){const records=profile.items?.accessories||[],candidates=records.filter(record=>record.canRecombobulate&&record.unrecombobulatedCount>0).sort((a,b)=>(rarityMeta[a.rarity]?.rank||99)-(rarityMeta[b.rarity]?.rank||99)||a.name.localeCompare(b.name)),ready=candidates.reduce((sum,record)=>sum+record.unrecombobulatedCount,0),recombined=records.reduce((sum,record)=>sum+record.recombobulatedCount,0);$('#recombReadyCount').textContent=ready;$('#recombinedCount').textContent=recombined;$('#recombCandidates').innerHTML=candidates.length?candidates.map(record=>`<span class="recomb-candidate"><strong>${escapeHtml(record.name)}${record.unrecombobulatedCount>1?` ×${record.unrecombobulatedCount}`:''}</strong><small>${escapeHtml(record.rarity||'Unknown')} → ${escapeHtml(nextRarity(record.rarity))}</small></span>`).join(''):'<p>Every eligible owned accessory is already recombobulated.</p>';$('#recombPanel').hidden=!profile.rawSignals?.accessoryMetadataAvailable}
const PUBLIC_PROFILE_API='https://statsapi.tem.cx';
const collectionAliases={OAK_LOG:'LOG',SPRUCE_LOG:'LOG:1',BIRCH_LOG:'LOG:2',JUNGLE_LOG:'LOG:3',ACACIA_LOG:'LOG_2',DARK_OAK_LOG:'LOG_2:1',COCOA_BEANS:'INK_SACK:3',LAPIS_LAZULI:'INK_SACK:4',POTATO:'POTATO_ITEM',PORKCHOP:'PORK',CHICKEN:'RAW_CHICKEN',COD:'RAW_FISH',END_STONE:'ENDER_STONE',NETHER_WART:'NETHER_STALK',CLAY:'CLAY_BALL',GLOWSTONE:'GLOWSTONE_DUST'};
const stripFormatting=value=>String(value||'').replace(/§[0-9A-FK-OR]/gi,'');
const normalizedName=value=>String(value||'').toLowerCase().replaceAll('_','');
function catalogItemForProfileId(id){const direct=accessories.find(item=>(item.profileIds||[item.id]).includes(id));if(direct)return direct;const family=Object.entries(familyUpgrades).find(([,ids])=>ids.includes(id))?.[0];return family?[...accessories.filter(item=>item.family===family)].sort((a,b)=>b.order-a.order)[0]:null}
function normalizePublicProfile(data){
  const member=data.member||{},inventoryGroups=Object.values(member.inventories||{}).filter(Array.isArray),ids=new Set(),counts={};
  for(const items of inventoryGroups)for(const item of items.filter(Boolean)){const id=String(item.id||'').toUpperCase(),amount=Math.max(1,Number(item.count)||1);if(!id)continue;ids.add(id);counts[id]=(counts[id]||0)+amount}
  const bag=(member.inventories?.accessory_bag||[]).filter(Boolean),rawAccessoryRecords=bag.map(item=>{const id=String(item.id||'').toUpperCase(),lore=item.display?.lore||[],rarityLine=lore.find(line=>/(?:VERY SPECIAL|SPECIAL|DIVINE|MYTHIC|LEGENDARY|EPIC|RARE|UNCOMMON|COMMON) ACCESSORY/i.test(stripFormatting(line)))||'',rarity=stripFormatting(rarityLine).match(/(VERY SPECIAL|SPECIAL|DIVINE|MYTHIC|LEGENDARY|EPIC|RARE|UNCOMMON|COMMON) ACCESSORY/i)?.[1]?.replaceAll(' ','_')||null,descriptor=profileAccessoryDescriptor(id),catalogItem=descriptor?.catalogItem||null,recombobulated=/§k/i.test(rarityLine),baseRarity=recombobulated?(rarityBefore(rarity)||catalogItem?.rarity||rarity):(descriptor?.external?rarity:catalogItem?.rarity||rarity),magicalPower=Number(String(lore.find(line=>line.includes('Accessory Power'))||'').match(/\+([\d,]+)/)?.[1]?.replaceAll(',','')||0),amount=Math.max(1,Number(item.count)||1);return{id,name:stripFormatting(item.display?.name)||catalogItem?.name||id,rarity,baseRarity,count:amount,recombobulated,canRecombobulate:catalogItem?.canRecombobulate===true,magicalPower,familyKey:descriptor?.family||`item:${id}`,familyLevel:descriptor?.level||0}});
  const activeByFamily=new Map();for(const record of rawAccessoryRecords){const current=activeByFamily.get(record.familyKey),recordRarity=rarityMeta[normalizeRarity(record.rarity)]?.rank||0,currentRarity=rarityMeta[normalizeRarity(current?.rarity)]?.rank||0;if(!current||record.familyLevel>current.familyLevel||(record.familyLevel===current.familyLevel&&(recordRarity>currentRarity||(recordRarity===currentRarity&&record.magicalPower>current.magicalPower))))activeByFamily.set(record.familyKey,record)}
  const accessoryRecords=[...activeByFamily.values()].map(record=>({...record,count:1,recombobulatedCount:record.recombobulated?1:0,unrecombobulatedCount:record.recombobulated?0:1})),accessoryIds=accessoryRecords.map(record=>record.id);
  const collections={};for(const entry of member.collections||[]){const raw=String(entry.name||'').toUpperCase(),id=collectionAliases[raw]||raw,amount=Number(entry.amount)||0;collections[raw]=amount;collections[id]=amount}
  const skills={};for(const entry of member.skills?.list||[]){const id=String(entry.id||'').toUpperCase(),xp=Number(entry.xp)||0;skills[id]=xp;skills[`SKILL_${id}`]=xp}
  const slayers={};for(const boss of member.slayers?.bosses||[])slayers[String(boss.rawName||boss.name||'').toLowerCase()]=Number(boss.level)||0;
  const crafted=[];for(const record of member.minions||[]){const minion=minions.find(candidate=>normalizedName(candidate.id)===normalizedName(record.name));if(!minion)continue;(record.levels||[]).forEach((done,index)=>{if(done&&minion.tiers[index])crafted.push(minion.tiers[index].id)})}
  const magicalPower=accessoryRecords.reduce((sum,record)=>sum+(record.magicalPower||magicalPowerFor(record.rarity)),0);
  return{source:'public-web',player:{username:member.username,uuid:member.uuid},profile:{id:data.profile?.uuid,name:data.profile?.name,mode:data.profile?.mode||'stranded',lastSave:member.lastSave||null},stats:{magicalPower},items:{ids:[...ids],accessoryIds,counts,accessories:accessoryRecords},collections,slayers,skills,minions:{crafted},cache:{hit:false,ageSeconds:0},rawSignals:{inventoryAvailable:ids.size>0,accessoryMetadataAvailable:accessoryRecords.length>0,collectionsAvailable:Object.keys(collections).length>0,slayersAvailable:Object.keys(slayers).length>0,minionsAvailable:crafted.length>0}};
}
async function fetchPublicStrandedProfile(username,profileName=''){
  const summaryResponse=await fetch(`${PUBLIC_PROFILE_API}/player/${encodeURIComponent(username)}?customization=true`),summary=await summaryResponse.json().catch(()=>null);
  if(!summaryResponse.ok)throw new Error(summary?.error||'That Minecraft player could not be found.');
  const strandedProfiles=(summary.profiles||[]).filter(candidate=>candidate.mode==='stranded');
  if(!strandedProfiles.length)throw new Error('No Stranded profile was found for that player.');
  if(!profileName&&strandedProfiles.length>1)return{selectionRequired:true,profiles:strandedProfiles.map(candidate=>({id:candidate.uuid,name:candidate.name}))};
  const chosen=profileName?strandedProfiles.find(candidate=>candidate.name.toLowerCase()===profileName.toLowerCase()):strandedProfiles[0];
  if(!chosen)throw new Error('That profile is not a Stranded profile.');
  const detailResponse=await fetch(`${PUBLIC_PROFILE_API}/player/${encodeURIComponent(username)}/${encodeURIComponent(chosen.name)}?customization=true`),detail=await detailResponse.json().catch(()=>null);
  if(!detailResponse.ok)throw new Error(detail?.error||'The Stranded profile could not be loaded.');
  return normalizePublicProfile(detail);
}
function showProfileChoices(username,profiles){profileOptionsUsername=username.toLowerCase();$('#profileSelect').innerHTML=profiles.map(candidate=>`<option value="${escapeHtml(candidate.name)}">${escapeHtml(candidate.name)}</option>`).join('');$('#profileChoiceField').hidden=false}
function hideProfileChoices(){profileOptionsUsername='';$('#profileChoiceField').hidden=true;$('#profileSelect').innerHTML=''}
function updateProfileSubmitLabel(button=$('#profileForm').querySelector('button')){button.innerHTML=$('#profileChoiceField').hidden?'Check profile <span>→</span>':'Load profile <span>→</span>'}
function updateProfileSummary(){const statuses=accessories.map(itemStatus),owned=statuses.filter(status=>status==='owned').length,ready=statuses.filter(status=>status==='ready').length;$('#ownedCount').textContent=owned;$('#upgradeCount').textContent=ready;$('#missingCount').textContent=accessories.length-owned;$('#magicPower').textContent=Number.isFinite(profile.stats?.magicalPower)?profile.stats.magicalPower.toLocaleString():'—';const percent=Math.round(owned/accessories.length*100);$('#completionText').textContent=`${percent}% of obtainable accessories found`;$('#completionBar').style.width=`${percent}%`;$('#playerName').textContent=profile.player.username;$('#profileMeta').textContent=`${profile.profile.name} · ${profile.profile.mode} · live web data`;$('#playerAvatar').style.backgroundImage=`url(https://mc-heads.net/avatar/${profile.player.uuid}/64)`;$('#apiNotice').textContent=profile.rawSignals.inventoryAvailable?`Ownership and craft checks use the profile’s API-visible inventory, Ender Chest, Accessory Bag, and Personal Vault. Accessory Power and recombobulation use only the highest tier in each family; duplicate and lower-tier copies are ignored. Sack contents are not exposed by the public web provider.${profile.rawSignals.accessoryMetadataAvailable?' Recombobulation checks use each accessory’s decoded rarity marker.':''}`:'Inventory data was not returned, so ownership and material checks may be incomplete.';$('#profilePanel').hidden=false;statusFilter.hidden=false;updateRecombobulationSummary();render();renderMinions()}
$('#profileForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button'),error=$('#profileError'),username=$('#playerInput').value.trim(),chosenProfile=profileOptionsUsername===username.toLowerCase()?$('#profileSelect').value:'';button.disabled=true;button.textContent='Checking…';error.hidden=true;try{const result=await fetchPublicStrandedProfile(username,chosenProfile);if(result.selectionRequired){showProfileChoices(username,result.profiles);$('#profilePanel').hidden=true;updateProfileSubmitLabel(button);return}profile=result;updateProfileSummary()}catch(problem){error.textContent=problem.message;error.hidden=false}finally{button.disabled=false;updateProfileSubmitLabel(button)}});
$('#playerInput').addEventListener('input',()=>{if(profileOptionsUsername&&profileOptionsUsername!==$('#playerInput').value.trim().toLowerCase()){hideProfileChoices();updateProfileSubmitLabel()}});
$('#clearProfile').addEventListener('click',()=>{profile=null;hideProfileChoices();updateProfileSubmitLabel();$('#profilePanel').hidden=true;$('#recombPanel').hidden=true;statusFilter.hidden=true;statusFilter.value='all';render();renderMinions()});$('#rarityFilters').addEventListener('click',event=>{if(!event.target.dataset.rarity)return;activeRarity=event.target.dataset.rarity;document.querySelectorAll('#rarityFilters button').forEach(button=>button.classList.toggle('active',button===event.target));render()});[search,sourceFilter,statusFilter].forEach(element=>element.addEventListener('input',render));document.querySelectorAll('.view-toggle button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.view-toggle button').forEach(candidate=>candidate.classList.toggle('active',button===candidate));grid.classList.toggle('list-view',button.dataset.view==='list')}));
$('.feature-tabs').addEventListener('click',event=>{const tab=event.target.dataset.tab;if(!tab)return;document.querySelectorAll('.feature-tabs button').forEach(button=>button.classList.toggle('active',button===event.target));$('#accessoriesTab').hidden=tab!=='accessories';$('#minionsTab').hidden=tab!=='minions';$('#moneyTab').hidden=tab!=='money'});$('#minionCategories').addEventListener('click',event=>{if(!event.target.dataset.category)return;activeMinionCategory=event.target.dataset.category;document.querySelectorAll('#minionCategories button').forEach(button=>button.classList.toggle('active',button===event.target));renderMinions()});[$('#minionSearch'),$('#minionStatus'),$('#minionSort')].forEach(element=>element.addEventListener('input',renderMinions));
const VILLAGER_SALE_ITEMS=[
  {id:'small-pocket-black-hole',name:'Small Pocket Black Hole',plural:'Small Pocket Black Holes',emeraldCost:16,costLabel:'16 Emeralds',npcSell:50000,tier:1},
  {id:'hellfire-rod',name:'Hellfire Rod',plural:'Hellfire Rods',emeraldCost:2560,costLabel:'16 Enchanted Emeralds',npcSell:5634000,tier:5},
  {id:'inferno-rod',name:'Inferno Rod',plural:'Inferno Rods',emeraldCost:640,costLabel:'4 Enchanted Emeralds',npcSell:1028000,tier:3},
  {id:'medium-pocket-black-hole',name:'Medium Pocket Black Hole',plural:'Medium Pocket Black Holes',emeraldCost:320,costLabel:'2 Enchanted Emeralds',npcSell:500000,tier:3}
];
const CALCULATOR_STORAGE_KEY='stranded-villager-money-calculator',LEGACY_CALCULATOR_STORAGE_KEY='stranded-small-black-hole-calculator';
const calculatorNumber=new Intl.NumberFormat('en-US',{maximumFractionDigits:2});
const calculatorCoins=new Intl.NumberFormat('en-US',{maximumFractionDigits:0});
const selectedSaleItem=()=>VILLAGER_SALE_ITEMS.find(item=>item.id===$('#saleItem').value)||VILLAGER_SALE_ITEMS[0];
function updateCalculatorRoute(item){const coinsPerEmerald=item.npcSell/item.emeraldCost;$('#calculatorTitle').textContent=`${item.name} calculator`;$('#calculatorDescription').textContent=`Convert Cocoa Beans into Emeralds, buy a ${item.name} for ${item.costLabel}, then sell it to an NPC for ${calculatorCoins.format(item.npcSell)} coins.`;$('#coinsPerEmerald').textContent=calculatorNumber.format(coinsPerEmerald);$('#routeCost').textContent=item.costLabel;$('#routeItem').textContent=`1 ${item.name}`;$('#routeSell').textContent=`${calculatorCoins.format(item.npcSell)} coins`;$('#itemsPerHourLabel').textContent=`${item.plural} / hour`;$('#calculatorNote').textContent=`Long-run gross value before any NPC sell limit. Partial ${item.plural.toLowerCase()} are treated as average value.`}
function setCalculatorResults(values){$('#emeraldsPerMinute').textContent=values?calculatorNumber.format(values.emeraldsPerMinute):'—';$('#itemsPerHour').textContent=values?calculatorNumber.format(values.itemsPerHour):'—';$('#coinsPerMinute').textContent=values?calculatorCoins.format(values.coinsPerMinute):'—';$('#coinsPerHour').textContent=values?calculatorCoins.format(values.coinsPerHour):'—';$('#coinsPerDay').textContent=values?calculatorCoins.format(values.coinsPerDay):'—'}
function calculateMoney(){const item=selectedSaleItem(),cocoaPerEmerald=Number($('#cocoaPerEmerald').value),cocoaPerMinute=Number($('#cocoaPerMinute').value);updateCalculatorRoute(item);const valid=Number.isFinite(cocoaPerEmerald)&&cocoaPerEmerald>0&&Number.isFinite(cocoaPerMinute)&&cocoaPerMinute>=0;$('#calculatorError').hidden=valid;if(!valid){setCalculatorResults(null);return}const emeraldsPerMinute=cocoaPerMinute/cocoaPerEmerald,itemsPerHour=emeraldsPerMinute*60/item.emeraldCost,coinsPerHour=itemsPerHour*item.npcSell;setCalculatorResults({emeraldsPerMinute,itemsPerHour,coinsPerMinute:coinsPerHour/60,coinsPerHour,coinsPerDay:coinsPerHour*24});try{localStorage.setItem(CALCULATOR_STORAGE_KEY,JSON.stringify({saleItem:item.id,cocoaPerEmerald,cocoaPerMinute}))}catch{}}
function initializeMoneyCalculator(){const saleItem=$('#saleItem');saleItem.innerHTML=VILLAGER_SALE_ITEMS.map((item,index)=>`<option value="${item.id}">#${index+1} · ${item.name} · T${item.tier} · ${calculatorNumber.format(item.npcSell/item.emeraldCost)}/emerald</option>`).join('');try{const saved=JSON.parse(localStorage.getItem(CALCULATOR_STORAGE_KEY)||localStorage.getItem(LEGACY_CALCULATOR_STORAGE_KEY));if(saved&&VILLAGER_SALE_ITEMS.some(item=>item.id===saved.saleItem))saleItem.value=saved.saleItem;if(saved&&Number.isFinite(saved.cocoaPerEmerald)&&saved.cocoaPerEmerald>0)$('#cocoaPerEmerald').value=saved.cocoaPerEmerald;if(saved&&Number.isFinite(saved.cocoaPerMinute)&&saved.cocoaPerMinute>=0)$('#cocoaPerMinute').value=saved.cocoaPerMinute}catch{}[$('#cocoaPerEmerald'),$('#cocoaPerMinute')].forEach(input=>input.addEventListener('input',calculateMoney));saleItem.addEventListener('change',calculateMoney);$('#moneyCalculator').addEventListener('submit',event=>{event.preventDefault();calculateMoney()});calculateMoney()}
initializeMoneyCalculator();
loadCatalog().then(()=>{document.documentElement.dataset.appReady='ready'}).catch(error=>{document.documentElement.dataset.appReady='error';grid.innerHTML=`<div class="profile-error">${error.message}. Reload the page and try again.</div>`});
